export const ACTION_TYPE ={
    updateUser: "UPDATE_USER",
    updateUserName: "UPDATE_NAME",
    openBookRoom: "OPEN_BOOK_ROOM",
    closeBookRoom: "CLOSE_BOOK_ROOM",
    setLoading: "SET_LOADING",
    changeLike: "CHANGE_LIKE",

    setModalComment: `SET_MODAL_COMMENT`,
    openModalComment: `OPEN_MODAL_COMMENT`,
    closeModalComment: `CLOSE_MODAL_COMMENT`,

    openModalUpdateRoomSerivce: 'OPEN_MODAL_UPDATE_ROOM_SERVICE',
    closeModalUpdateRoomSerivce: 'CLOSE_MODAL_UPDATE_ROOM_SERVICE',
    openModalUpdateUser: 'OPEN_MODAL_UPDATE_USER',
    closeModalUpdateUser: 'CLOSE_MODAL_UPDATE_USER',
    openModalUpdateRoom: "OPEN_MODAL_UPDATE_ROOM",
    closeModalUpdateRoom: "CLOSE_MODAL_UPDATE_ROOM",
    openModalUpdatePhoto: "OPEN_MODAL_UPDATE_PHOTO",
    closeModalUpdatePhoto: "CLOSE_MODAL_UPDATE_PHOTO",
    openModalUpdateContract: "OPEN_MODAL_UPDATE_CONTRACT",
    closeModalUpdateContract: "CLOSE_MODAL_UPDATE_CONTRACT",
    openModalUpdateService: "OPEN_MODAL_UPDATE_SERVICE",
    closeModalUpdateService: "CLOSE_MODAL_UPDATE_SERVICE",

    openModalDeleteRoomService: "OPEN_MODAL_DELETE_ROOM_SERVICE",
    closeModalDeleteRoomService: "CLOSE_MODAL_DELETE_ROOM_SERVICE",
    openModalDeleteService: "OPEN_MODAL_DELETE_SERVICE",
    closeModalDeleteService: "CLOSE_MODAL_DELETE_SERVICE",
    openModalDeleteUser: 'OPEN_MODAL_DELETE_USER',
    closeModalDeleteUser: 'CLOSE_MODAL_DELETE_USER',
    openModalDeleteRoom: "OPEN_MODAL_DELETE_ROOM",
    closeModalDeleteRoom: "CLOSE_MODAL_DELETE_ROOM",
    openModalDeletePhoto: "OPEN_MODAL_DELETE_PHOTO",
    closeModalDeletePhoto: "CLOSE_MODAL_DELETE_PHOTO",
    openModalDeleteContract: "OPEN_MODAL_DELETE_CONTRACT",
    closeModalDeleteContract: "CLOSE_MODAL_DELETE_CONTRACT",


    openModalCreateRoomService: "OPEN_MODAL_CREATE_ROOM_SERVICE",
    closeModalCreateRoomService: "CLOSE_MODAL_CREATE_ROOM_SERVICE",
    openModalCreateService: 'OPEN_MODAL_CREATE_SERVICE',
    closeModalCreateService: 'CLOSE_MODAL_CREATE_SERVICE',
    openModalCreateUser: 'OPEN_MODAL_CREATE_USER',
    closeModalCreateUser: 'CLOSE_MODAL_CREATE_USER',
    openModalCreateRoom: "OPEN_MODAL_CREATE_ROOM",
    closeModalCreateRoom: "CLOSE_MODAL_CREATE_ROOM",
    openModalCreatePhoto: "OPEN_MODAL_CREATE_PHOTO",
    closeModalCreatePhoto: "CLOSE_MODAL_CREATE_PHOTO",
    openModalCreateContract: "OPEN_MODAL_CREATE_CONTRACT",
    closeModalCreateContract: "CLOSE_MODAL_CREATE_CONTRACT",
}